<?php
    require_once("../../includes/sesion.php");
    require_once("../../includes/connection.php");

    function getExifData($temp_path, $extension) {
        //EXIF DATA
		// exif_read_data() reads the EXIF headers from a JPEG or TIFF image file. This way you
		// can read meta data generated by digital cameras.
        $exif_data = '';

        if ($extension == 'jpg'){
			if (exif_read_data($temp_path, 0, true)) {
				$exif = exif_read_data($temp_path, 0, true);

				if (isset($exif['FILE']['FileSize']) && isset($exif['IFD0']['Copyright'])) {
					$exif_data =  $exif['IFD0']['Copyright'];
				}
			}
		}

        return $exif_data;
    }

    function getFileExtension($fileName) {
		$ex_ext = explode('.', $fileName);
		$extension = end($ex_ext);

		return strtolower($extension);
    }

    function getFileName($file) {
        $fileName = basename($file['name']);

        return preg_replace('#[^a-z.0-9_-]#i', "-", $fileName);
    }

    function cropImages($ruta1, $ruta2, $ruta3, $extension) {
        require_once("img_reduccion.php");

        $archivo_origen = $ruta3;
        $destino_medianas = $ruta2;
        $ruta_pequenas = $ruta1;

        reducir_imagen($archivo_origen, $destino_medianas, $extension, $ruta_pequenas);
    }

    function getPaths($fileName) {
        $DESTINATION_PARENT_FOLDER_PATH = '../../imagenes/';
        $RECORDING_PARENT_FOLDER_PATH = 'imagenes/';

        if (!isset($fileName)) {
            echo 'the file name is not set';
            return;
        }

        return [
            'destination_paths' => [
                $DESTINATION_PARENT_FOLDER_PATH . "pequenas/" . $fileName,
                $DESTINATION_PARENT_FOLDER_PATH . "medianas/" . $fileName,
                $DESTINATION_PARENT_FOLDER_PATH . "grandes/" . $fileName
            ],
            'recording_paths' => [
                $RECORDING_PARENT_FOLDER_PATH . "pequenas/" . $fileName,
                $RECORDING_PARENT_FOLDER_PATH . "medianas/" . $fileName,
                $RECORDING_PARENT_FOLDER_PATH . "grandes/" . $fileName
            ]
        ];
    }

    function redirectPage($albumId) {
        $redirectionUrl = "../../editar-galeria.php?album_id=" . $albumId . "&album=" . $_POST['album'];

        if (isset($_POST['type'])) {
            $redirectionUrl = $redirectionUrl . "&tipo=instalacion";
        }

        header("Location: {$redirectionUrl}&act=1");
    }

    function createImageOrVideoRecord($fileName, $extension, $exifData) {
        global $connection;
        date_default_timezone_set('America/Bogota');
		$fecha = date("Y-m-j");

        $tabla = $_POST['tabla'];
		$id = $_POST['campo_id'];
		$campo = $_POST['campo'];
 
        $destination_paths = getPaths($fileName)['destination_paths'];
        $recording_paths = getPaths($fileName)['recording_paths'];

        $sql  = "INSERT INTO $tabla (
            {$campo},
            fecha_creacion,
            exif_data,
            imagen1,
            imagen2,
            imagen3
        ) VALUES (
            $id,
            '{$fecha}',
            '{$exifData}',
            '{$recording_paths[0]}',
            '{$recording_paths[1]}',
            '{$recording_paths[2]}'
        )";

        if (mysql_query($sql, $connection) && mysql_affected_rows() == 1) {
            echo mysql_error();
        }

        cropImages($destination_paths[0], $destination_paths[1], $destination_paths[2], $extension);
        redirectPage($_POST['campo_id']);
    }

    function uploadImage($temp_path, $fileName, $extension) {
        $destination_paths = getPaths($fileName)['destination_paths'];
        $exifData = getExifData($temp_path, $extension);

        if (move_uploaded_file($temp_path, $destination_paths[2])) {
            createImageOrVideoRecord($fileName, $extension, $exifData);
        } else {
            $mensaje = "NADA" . mysql_error();
        }
    }

    function getCurl($url) {
        $curl = curl_init($url);

        curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($curl, CURLOPT_TIMEOUT, 30);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, 1);

        $response = curl_exec($curl);
        curl_close($curl);

        return $response;
    }

    function getVideoData() {
        $videoUrl = 'http://vimeo.com/' . $_POST['videoKey'];
        $oembed_endpoint = 'http://vimeo.com/api/oembed';

        $json_url = $oembed_endpoint . '.json?url=' . rawurlencode($videoUrl) . '&width=640';
        $xml_url = $oembed_endpoint . '.xml?url=' . rawurlencode($videoUrl) . '&width=640';

        return getCurl($xml_url);
    }

    function isertVideoEntry($formattedVideoData) {
        global $connection;

        date_default_timezone_set('America/Bogota');
		$insertionDate = date("Y-m-j");

        $data = $formattedVideoData;
        $title = $data->title;
        $thumbNail = $data->thumbnail_url;
        $videoKey = $data->video_id;
        $videoHTML = $data->html;
        $type = 'video';

        $query = "INSERT INTO imagenes_albums (
            album_id,
            fecha_creacion,
            titulo,
            tipo,
            video_key,
            video_html,
            imagen1,
            imagen2,
            imagen3
        ) VALUES (
            " . $_POST['albumId'] . ",
            '{$insertionDate}',
            '{$title}',
            '{$type}',
            '{$videoKey}',
            '{$videoHTML}',
            '{$thumbNail}',
            '{$thumbNail}',
            '{$thumbNail}'
        )";

        if (mysql_query($query, $connection) && mysql_affected_rows() == 1) {
            redirectPage($_POST['albumId']);
        } else {
            echo mysql_error();
        }
    }

    function validateFile($file, $extension) {
        $extensions = ['jpg', 'png'];

        if ($file['error'] == 1) {
			$mensaje = '<div id="mensaje_negativo">el archivo que seleccionaste es demasiado grande</div>';
		} else if ($file['error'] == 4) {
			$mensaje = '<div id="mensaje_negativo">no has seleccionado una imagen</div>';
		} else if (file_exists('imagenes/pequenas/' . getFileName($file)) ){
			$mensaje = '<div id="mensaje_negativo">el archivo ya existe, seleciona otro diferente o cambia el nombre</div>';
		} else if ($extension != $extensions[0] && $extension != $extensions[1]){
			$mensaje = '<div id="mensaje_negativo">el tipo de archivos no es valido</div>';
		} else {
            return 'isValid';
		}
    }

	if (isset($_POST['insertar_imagen'])) {
		$file = $_FILES['nombre_archivo'];
        $nombre_archivo = getFileName($file);
        $extension = getFileExtension($nombre_archivo);
        $isValidFile = validateFile($file, $extension) == 'isValid';

        if ($isValidFile) {
            uploadImage($file['tmp_name'], $nombre_archivo, $extension);
        }
	} else if (isset($_POST['insertVideo']) && isset($_POST['videoKey'])) {
        $videoData = getVideoData();

        if ($videoData != '404 Not Found') {
            $formattedVideoData = simplexml_load_string($videoData);
            //print("<pre>" . print_r($formattedVideoData, true) . "</pre>");
            isertVideoEntry($formattedVideoData);
        } else {
            echo 'no valid video key';
        }
    }
?>

